import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST() {
  const sql = `
-- Create table for broken link reports
create table if not exists public.broken_link_reports (
  id bigint generated by default as identity primary key,
  agency_id text,
  agency_name text,
  report_text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.broken_link_reports enable row level security;

-- Create policy to allow inserts for all users (public)
create policy "Anyone can insert broken link reports" on public.broken_link_reports for insert with check (true);

-- Create policy to allow admin to read all reports
create policy "Admin can read all broken link reports" on public.broken_link_reports for select using (true);

-- Add index for agency_name for better query performance
create index if not exists broken_link_reports_agency_name_idx on public.broken_link_reports(agency_name);

-- Add index for created_at for sorting
create index if not exists broken_link_reports_created_at_idx on public.broken_link_reports(created_at desc);
  `;

  try {
    const { data, error } = await supabase.rpc('exec_sql', { sql });

    if (error) {
      console.error('SQL Error:', error);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error('Error:', error);
    return NextResponse.json({ error: 'Failed to execute migration' }, { status: 500 });
  }
}
