import { InsuranceType, Provider, Question } from './types';

export const INSURANCE_TYPES: Record<string, InsuranceType> = {
  HEALTH: {
    key: 'HEALTH',
    title: 'Sağlık Sigortası (Krankenversicherung)',
    base: 10,
    mustAt: 12,
    shouldAt: 9,
    reasons: [
      'Almanya\'da sağlık sigortası çoğu senaryoda temel/olmazsa olmazdır.',
      'Kapsam türü (GKV/PKV) iş durumu ve gelire göre değişebilir.',
      'Kontrol et: GKV/PKV uygunluğu, aile kapsamı, ek katkılar, bekleme/şartlar.',
    ],
  },
  LIABILITY: {
    key: 'LIABILITY',
    title: 'Özel Sorumluluk (Privathaftpflicht)',
    base: 8,
    mustAt: 11,
    shouldAt: 8,
    reasons: [
      'Üçüncü kişiye verilen maddi/bedeni zararlar çok pahalıya çıkabilir.',
      'Günlük hayatta en çok \'fayda/ücret\' oranı yüksek kalemlerden biridir.',
      'Kontrol et: teminat limiti, aile kapsamı, anahtar kaybı gibi ekler.',
    ],
  },
  CAR: {
    key: 'CAR',
    title: 'Araç Sigortası (Kfz-Haftpflicht + opsiyonel kasko)',
    base: 0,
    mustAt: 5,
    shouldAt: 3,
    reasons: [
      'Araç varsa trafik sorumluluk sigortası çoğu durumda zorunlu kabul edilir.',
      'Kasko ihtiyacı aracın değeri ve risk iştahına göre değişir.',
      'Kontrol et: sınıf/prim, hasarsızlık indirimi, kasko kapsamı.',
    ],
  },
  HOUSEHOLD: {
    key: 'HOUSEHOLD',
    title: 'Ev Eşyası (Hausrat)',
    base: 2,
    mustAt: 8,
    shouldAt: 5,
    reasons: [
      'Hırsızlık/yangın/su gibi risklerde eşyayı korumaya yarar.',
      'Pahalı eşyalar ve kiracılık senaryosunda daha anlamlı hale gelebilir.',
      'Kontrol et: teminat tutarı, bisiklet kapsamı, muafiyet.',
    ],
  },
  LEGAL: {
    key: 'LEGAL',
    title: 'Hukuk Koruma (Rechtsschutz)',
    base: 1,
    mustAt: 9,
    shouldAt: 5,
    reasons: [
      'İş/ev/taşınma dönemlerinde ihtilaf çıkarsa masrafları azaltabilir.',
      'Kapsam paketleri (iş, kira, trafik) ayrı ayrı değerlidir.',
      'Kontrol et: bekleme süresi, kapsam dışı haller, limitler.',
    ],
  },
  BU: {
    key: 'BU',
    title: 'Çalışamazlık / Gelir Koruma (Berufsunfähigkeit)',
    base: 1,
    mustAt: 10,
    shouldAt: 6,
    reasons: [
      'Gelir kesilmesi seni zorluyorsa güçlü bir "risk yönetimi" kalemidir.',
      'Primler yaş, meslek ve sağlık beyanlarına göre değişir.',
      'Kontrol et: tanım (BU), aylık ödeme, beyan/sağlık şartları.',
    ],
  },
  LIFE: {
    key: 'LIFE',
    title: 'Risk Hayat (Risikolebensversicherung)',
    base: 0,
    mustAt: 8,
    shouldAt: 4,
    reasons: [
      'Bakmakla yükümlü olunan kişiler varsa gelir kaybı riskini yönetir.',
      'Mortgage/uzun vadeli taahhütlerde anlamı artar.',
      'Kontrol et: teminat süresi, lehtar, prim/sağlık beyanı.',
    ],
  },
  DENTAL: {
    key: 'DENTAL',
    title: 'Diş Tamamlayıcı (Zahnzusatz)',
    base: 0,
    mustAt: 7,
    shouldAt: 4,
    reasons: [
      'Diş işlemleri pahalı olabilir; beklentin yüksekse değerlendirilebilir.',
      'Kapsam ve bekleme süreleri poliçeye göre değişir.',
      'Kontrol et: bekleme süresi, yıllık limitler, kapsam oranları.',
    ],
  },
  ACCIDENT: {
    key: 'ACCIDENT',
    title: 'Kaza Sigortası (Unfallversicherung)',
    base: 0,
    mustAt: 7,
    shouldAt: 4,
    reasons: [
      'Riskli aktivite/yoğun hareket varsa ek koruma sağlar.',
      'Kaza tanımı ve ödeme şartları ürün bazında farklıdır.',
      'Kontrol et: kaza tanımı, sürekli sakatlık teminatı, kapsam dışıları.',
    ],
  },
  TRAVEL: {
    key: 'TRAVEL',
    title: 'Seyahat Sağlık (Auslandsreise-KV) / İptal (opsiyonel)',
    base: 0,
    mustAt: 7,
    shouldAt: 3,
    reasons: [
      'Sık yurt dışı seyahatinde acil sağlık masrafını yönetebilir.',
      'İptal sigortası sadece belirli senaryolarda mantıklıdır.',
      'Kontrol et: ülke kapsamı, azami süre, muafiyetler.',
    ],
  },
  BUILDING: {
    key: 'BUILDING',
    title: 'Konut Bina (Wohngebäude) — ev sahibiysen',
    base: 0,
    mustAt: 7,
    shouldAt: 3,
    reasons: [
      'Ev sahibiysen bina riskleri (yangın/su/fırtına) önemli olabilir.',
      'Kredi veren kuruluş koşul koyabilir (duruma göre).',
      'Kontrol et: kapsam (Elementar dahil mi), muafiyet, yeniden yapım değeri.',
    ],
  },
  PET_LIAB: {
    key: 'PET_LIAB',
    title: 'Evcil Hayvan Sorumluluk (Tierhalterhaftpflicht) — özellikle köpek',
    base: 0,
    mustAt: 7,
    shouldAt: 2,
    reasons: [
      'Köpek gibi hayvanlarda üçüncü şahıs riski artabilir.',
      'Kapsam hayvan türüne ve koşullara göre değişir.',
      'Kontrol et: teminat limiti, ırk/koşul istisnaları, aile kapsamı.',
    ],
  },
};

export const PROVIDERS: Record<string, Provider[]> = {
  HEALTH: [
    { name: 'TK (Techniker Krankenkasse)', desc: "Almanya'nın en büyük kamu sağlık sigortası (yaklaşık 11 milyon üye)", url: 'https://www.tk.de/' },
    { name: 'AOK', desc: 'Almanya genelinde yaygın bir kamu sağlık sigortası', url: 'https://www.aok.de/' },
    { name: 'Barmer', desc: "Almanya'nın en büyük kamu sağlık sigortalarından biri", url: 'https://www.barmer.de/' },
  ],
  LIABILITY: [
    { name: 'Getsafe', desc: 'Dijital sigorta şirketi, modern online hizmet sunar', url: 'https://getsafe.de' },
    { name: 'HUK-Coburg', desc: 'Geniş kapsamlı sorumluluk sigortası sunan köklü şirket', url: 'https://www.huk.de/' },
    { name: 'Allianz', desc: 'Dünya çapında büyük bir sigorta şirketi', url: 'https://www.allianz.de/' },
  ],
  CAR: [
    { name: 'HUK-Coburg', desc: "Almanya'da çok yaygın araç sigortası sağlayıcısı", url: 'https://www.huk.de/' },
    { name: 'Allianz', desc: 'Çeşitli araç sigortası seçenekleri sunan büyük şirket', url: 'https://www.allianz.de/' },
    { name: 'ADAC', desc: 'Alman otomobil kulübü, araç sigortası hizmetleri de sunar', url: 'https://www.adac.de/' },
  ],
  HOUSEHOLD: [
    { name: 'HUK-Coburg', desc: 'Ev eşyası sigortası sunan büyük sağlayıcı', url: 'https://www.huk.de/' },
    { name: 'Allianz', desc: 'Evcilik ve ev eşyası sigortalarında seçenekler sunar', url: 'https://www.allianz.de/' },
    { name: 'DEVK', desc: 'Çeşitli kişisel sigortalar sunan Alman sigorta şirketi', url: 'https://www.devk.de/' },
  ],
  LEGAL: [
    { name: 'ARAG', desc: 'Hukuk koruma sigortasında öncü ve yaygın sağlayıcı', url: 'https://www.arag.de/' },
    { name: 'D.A.S.', desc: "Almanya'da tanınan bir hukuk koruma sigortası markası", url: 'https://www.das.de/' },
    { name: 'Allianz', desc: 'Hukuk koruma sigortası da sunan büyük sigorta grubu', url: 'https://www.allianz.de/' },
  ],
  BU: [
    { name: 'Allianz', desc: "Almanya'nın en büyük sigortacılarından biri, gelir koruma sigortası sunar", url: 'https://www.allianz.de/' },
    { name: 'Debeka', desc: 'Devlet memurlarına yakın, uzun vadeli gelir koruma seçenekleri', url: 'https://www.debeka.de/' },
    { name: 'Signal Iduna', desc: 'Çeşitli mesleklere uygun meslek sakatlık sigortaları', url: 'https://www.signal-iduna.de/' },
  ],
  LIFE: [
    { name: 'Allianz', desc: 'Hayat sigortalarında geniş ürün yelpazesi sunan lider şirket', url: 'https://www.allianz.de/' },
    { name: 'Debeka', desc: 'Hayat sigortası alanında tanınan büyük sağlayıcı', url: 'https://www.debeka.de/' },
    { name: 'R+V', desc: 'Kooperatif yapısında, çeşitli risk hayat sigortası seçenekleri', url: 'https://www.ruv.de/' },
  ],
  DENTAL: [
    { name: 'HanseMerkur', desc: 'Tamamlayıcı diş sigortalarında yaygın bir sağlayıcı', url: 'https://www.hansemerkur.de/' },
    { name: 'DKV (Ergo)', desc: 'Diğer tamamlayıcı sigortalarla bilinen güçlü şirket', url: 'https://www.ergo.de/' },
    { name: 'Barmenia', desc: 'Diş sigortaları da sunan büyük sigorta şirketi', url: 'https://www.barmenia.de/' },
  ],
  ACCIDENT: [
    { name: 'Alte Oldenburger', desc: 'Yüzyılı aşkın süredir kaza sigortalarında uzman', url: 'https://www.alte-oldenburger.de/' },
    { name: 'HUK-Coburg', desc: 'Kaza sigortası da dahil çeşitli ürünler sunar', url: 'https://www.huk.de/' },
    { name: 'Allianz', desc: 'Kaza sigortası dahil geniş ürün seçenekleri sunan global şirket', url: 'https://www.allianz.de/' },
  ],
  TRAVEL: [
    { name: 'ADAC', desc: 'Seyahat sigortası da sunan otomobil kulübü', url: 'https://www.adac.de/' },
    { name: 'ERV (Allianz)', desc: "Almanya'nın öncü seyahat sigortası sağlayıcısı", url: 'https://www.ergo-reiseversicherung.de/' },
    { name: 'HanseMerkur', desc: 'Uygun fiyatlı seyahat sağlık sigortası seçenekleri', url: 'https://www.hansemerkur.de/' },
  ],
  BUILDING: [
    { name: 'Allianz', desc: 'Konut/bina sigortasında geniş seçenekler sunan lider şirket', url: 'https://www.allianz.de/' },
    { name: 'HUK-Coburg', desc: 'Konut sigortası da sunan geniş hizmet sağlayıcısı', url: 'https://www.huk.de/' },
    { name: 'DEVK (InterRisk)', desc: 'Bina sigortalarında önemli ürün seçenekleri', url: 'https://www.devk.de/' },
  ],
  PET_LIAB: [
    { name: 'HUK-Coburg', desc: 'Evcil hayvan sigortası da sunan tanınmış şirket', url: 'https://www.huk.de/' },
    { name: 'Allianz', desc: 'Köpek gibi hayvanlarda sorumluluk sigortası seçenekleri', url: 'https://www.allianz.de/' },
    { name: 'Uelzener', desc: 'Hayvan sigortaları konusunda uzmanlaşmış şirket', url: 'https://www.uelzener.de/' },
  ],
};

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    title: 'Almanya\'da ikamet edeceksin ve resmi kayıt (Anmeldung) yapacak mısın?',
    desc: 'Genel sistemlere giriş için ikamet ve kayıt süreçleri çoğu senaryoda temel kabul edilir.',
    type: 'yesno',
    weight: { yes: { HEALTH: 3 }, no: { HEALTH: 1 } },
  },
  {
    id: 'q2',
    title: 'Çalışan mısın? (tam zamanlı/yarı zamanlı/mini-job dışı düzenli iş)',
    desc: 'Çalışma şekli bazı sigorta kararlarını etkiler.',
    type: 'single',
    options: [
      { key: 'employee', label: 'Evet, çalışanım', desc: 'Düzenli bir işte çalışıyorum.', add: { HEALTH: 2, LIABILITY: 2, LEGAL: 1, BU: 2 } },
      { key: 'self', label: 'Serbest/şirket (freelance)', desc: 'Kendi işimin patronuyum.', add: { HEALTH: 2, LIABILITY: 2, LEGAL: 2, BU: 3 } },
      { key: 'student', label: 'Öğrenciyim', desc: 'Okula gidiyorum.', add: { HEALTH: 2, LIABILITY: 3 } },
      { key: 'other', label: 'Diğer/şu an çalışmıyorum', desc: 'İş arıyorum veya ev hanımıyım.', add: { HEALTH: 2, LIABILITY: 2 } },
    ],
  },
  {
    id: 'q3',
    title: 'Aileni (eş/çocuk) da kapsayan bir yapı gerekir mi?',
    desc: 'Aile durumu bazı poliçe tercihlerini değiştirir.',
    type: 'yesno',
    weight: { yes: { HEALTH: 2, LIFE: 2, HOUSEHOLD: 1 }, no: { BU: 1 } },
  },
  {
    id: 'q4',
    title: 'Araba kullanıyor musun veya Almanya\'da araba almayı planlıyor musun?',
    desc: 'Araç varsa sigorta tarafı farklı bir "zorunlu" kalem doğurabilir.',
    type: 'yesno',
    weight: { yes: { CAR: 5 }, no: { CAR: -2 } },
  },
  {
    id: 'q5',
    title: 'Evde pahalı eşyaların var mı? (laptop/TV/kamera, vb.)',
    desc: 'Hırsızlık/yangın/su basması gibi riskler değerlendirilir.',
    type: 'yesno',
    weight: { yes: { HOUSEHOLD: 3 }, no: { HOUSEHOLD: 1 } },
  },
  {
    id: 'q6',
    title: 'Kiracı mısın, ev sahibi mi olacaksın?',
    desc: 'Ev sahipliği bazı ek sigorta türlerini gündeme getirir.',
    type: 'single',
    options: [
      { key: 'rent', label: 'Kiracı', desc: 'Kiralık bir evde yaşıyorum.', add: { HOUSEHOLD: 2, LIABILITY: 1 } },
      { key: 'own', label: 'Ev sahibi', desc: 'Kendi evim var veya alacağım.', add: { BUILDING: 5, LIABILITY: 1, HOUSEHOLD: 2 } },
      { key: 'not_sure', label: 'Henüz belli değil', desc: 'Kararsızım.', add: { HOUSEHOLD: 1 } },
    ],
  },
  {
    id: 'q7',
    title: 'Çocukların var mı?',
    desc: 'Aile riskleri ve gelir güvenliği daha kritik hale gelebilir.',
    type: 'yesno',
    weight: { yes: { LIFE: 3, BU: 2, HEALTH: 1 }, no: { LIABILITY: 1 } },
  },
  {
    id: 'q8',
    title: 'Düzenli olarak bisiklet/e-scooter kullanıyor musun?',
    desc: 'Günlük şehir içi kullanımda üçüncü şahıs zararları önemli olabilir.',
    type: 'yesno',
    weight: { yes: { LIABILITY: 2, ACCIDENT: 1 }, no: { ACCIDENT: 0 } },
  },
  {
    id: 'q9',
    title: 'Sık seyahat ediyor musun? (AB içi/dışı)',
    desc: 'Seyahat sağlık ekleri ve iptal gibi konular ancak bazı senaryolarda anlamlıdır.',
    type: 'single',
    options: [
      { key: 'often', label: 'Evet, sık', desc: 'Yılda birkaç kez yurt dışına çıkıyorum.', add: { TRAVEL: 4 } },
      { key: 'sometimes', label: 'Ara sıra', desc: 'Yılda bir kez olabilir.', add: { TRAVEL: 2 } },
      { key: 'rare', label: 'Nadiren', desc: 'Neredeyse hiç seyahat etmiyorum.', add: { TRAVEL: 0 } },
    ],
  },
  {
    id: 'q10',
    title: 'Bir hata yapıp başkasına zarar verme riskin yüksek mi? (çocuk, evcil hayvan, yoğun sosyal hayat)',
    desc: 'Örneğin birine maddi/bedeni zarar verme gibi riskler.',
    type: 'yesno',
    weight: { yes: { LIABILITY: 4 }, no: { LIABILITY: 2 } },
  },
  {
    id: 'q11',
    title: 'Gelirin kesilmesi seni ciddi zorlar mı? (tek gelir, az birikim, kredi/taahhüt)',
    desc: 'Çalışamaz hale gelme gibi senaryolarda "gelir koruma" daha anlamlı hale gelebilir.',
    type: 'yesno',
    weight: { yes: { BU: 5 }, no: { BU: 1 } },
  },
  {
    id: 'q12',
    title: 'Hukuki ihtilaf yaşama ihtimalin var mı? (iş/ev/komşu/taşınma)',
    desc: 'Kiracı-ev sahibi, iş sözleşmesi, tüketici anlaşmazlıkları gibi.',
    type: 'yesno',
    weight: { yes: { LEGAL: 4 }, no: { LEGAL: 1 } },
  },
  {
    id: 'q13',
    title: 'Diş masrafları seni düşündürüyor mu? (ortodonti, implant, vb.)',
    desc: 'Tamamlayıcı diş sigortası bazı kişilerde anlamlı olabilir.',
    type: 'yesno',
    weight: { yes: { DENTAL: 4 }, no: { DENTAL: 0 } },
  },
  {
    id: 'q14',
    title: 'Riskli/hobisel aktivitelerin var mı? (dağ sporu, motor, ekstrem spor)',
    desc: 'Kaza ihtimali artıyorsa kaza sigortası öne çıkabilir.',
    type: 'yesno',
    weight: { yes: { ACCIDENT: 4 }, no: { ACCIDENT: 1 } },
  },
  {
    id: 'q15',
    title: 'Evcil hayvanın var mı? (özellikle köpek)',
    desc: 'Bazı hayvanlarda üçüncü şahıs riski artar.',
    type: 'single',
    options: [
      { key: 'dog', label: 'Köpek', desc: 'Köpeğim var.', add: { PET_LIAB: 5 } },
      { key: 'cat', label: 'Kedi', desc: 'Kedim var.', add: { PET_LIAB: 1 } },
      { key: 'none', label: 'Yok', desc: 'Evcil hayvanım yok.', add: { PET_LIAB: 0 } },
    ],
  },
  {
    id: 'q16',
    title: 'Tehlikeli bir işte/ortamda mı çalışıyorsun? (inşaat, yüksekten çalışma, vb.)',
    desc: 'Fiziksel olarak riskli işlerde kaza veya gelir kaybı riski artar.',
    type: 'yesno',
    weight: { yes: { ACCIDENT: 2, BU: 2 }, no: { ACCIDENT: 0 } },
  },
  {
    id: 'q17',
    title: 'Kredi veya büyük borcun var mı? (konut, taşıt vb.)',
    desc: 'Borçların varsa hayat sigortası ve gelir koruma daha önemli olabilir.',
    type: 'yesno',
    weight: { yes: { LIFE: 3, BU: 2 }, no: { LIFE: 0, BU: 0 } },
  },
  {
    id: 'q18',
    title: 'Riskli bir bölgede (sel, fırtına vb.) mı yaşıyorsun?',
    desc: 'Fiziki riskler arttıkça bina/eşya sigortaları daha anlamlı hale gelebilir.',
    type: 'yesno',
    weight: { yes: { BUILDING: 3, HOUSEHOLD: 1 }, no: { BUILDING: 0 } },
  },
  {
    id: 'q19',
    title: 'Günlük olarak başka araç kullanıyor musun? (motor, büyük taşıt vb.)',
    desc: 'Ek araç kullanımı üçüncü şahıs sorumluluğu ve kaza riskini artırır.',
    type: 'yesno',
    weight: { yes: { LIABILITY: 2, ACCIDENT: 2 }, no: { LIABILITY: 0 } },
  },
  {
    id: 'q20',
    title: 'Evde yangın veya su baskını riski var mı? (eski tesisat, fırtına riski)',
    desc: 'Bu tür riskler konut/bina ve ev eşyası sigortasını önemli kılar.',
    type: 'yesno',
    weight: { yes: { BUILDING: 3, HOUSEHOLD: 2 }, no: { BUILDING: 0 } },
  },
];
