-- Add 54 English-speaking companies to recruitment_agencies table
INSERT INTO recruitment_agencies (name, url, description, category, status) VALUES
('About You', 'https://corporate.aboutyou.de/de/career/our-jobs', 'E-commerce fashion platform with English job opportunities', 'English Hiring Companies', 'active'),
('Accenture', 'https://www.accenture.com/de-de/careers/jobsearch', 'Global consulting with English-speaking positions in Berlin', 'English Hiring Companies', 'active'),
('Accountable', 'https://join.com/companies/accountable', 'Financial services startup with English job openings', 'English Hiring Companies', 'active'),
('Acemate.ai', 'https://join.com/companies/acemate', 'AI-powered platform offering English-speaking roles', 'English Hiring Companies', 'active'),
('Babbel', 'https://jobs.babbel.com/en/', 'Language learning platform with international team opportunities', 'English Hiring Companies', 'active'),
('Personio', 'https://www.personio.com/about-personio/careers/', 'HR software company with English-speaking work environment', 'English Hiring Companies', 'active'),
('Banxware', 'https://www.banxware.com/careers', 'Fintech startup offering English job opportunities', 'English Hiring Companies', 'active'),
('BASF', 'https://basf.jobs/', 'Chemical industry leader with international English positions', 'English Hiring Companies', 'active'),
('BearingPoint', 'https://www.bearingpoint.com/en/careers/open-roles/', 'Management consulting with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Bettermile', 'https://bettermile.com/careers/', 'Logistics optimization platform with English job openings', 'English Hiring Companies', 'active'),
('Carbon One', 'https://www.carbon.one/#jobs', 'Carbon management startup with English-speaking roles', 'English Hiring Companies', 'active'),
('Caidera', 'https://www.caidera.ai/de/karriere', 'AI technology company offering English job opportunities', 'English Hiring Companies', 'active'),
('Calima', 'https://www.calima.io/jobs', 'Clean energy platform with English-speaking positions', 'English Hiring Companies', 'active'),
('Canva', 'https://www.lifeatcanva.com/en/jobs/', 'Design platform with international English job opportunities', 'English Hiring Companies', 'active'),
('Caresyntax', 'https://www.linkedin.com/company/caresyntax/', 'Healthcare AI company with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Cloover', 'https://cloover.notion.site/Join-us-Cloover-73ec11a2660748ecb6b66be87c10d4b8', 'Clean technology startup offering English job openings', 'English Hiring Companies', 'active'),
('Claire', 'https://clareandme.notion.site/Clare-needs-YOU-3acc2ce1815d402c8c6c6ea0ca5e3fd9', 'Digital assistant platform with English-speaking roles', 'English Hiring Companies', 'active'),
('Elearnio', 'https://careers.elearnio.com/jobs/Careers', 'E-learning platform with English job opportunities', 'English Hiring Companies', 'active'),
('Finmid', 'https://jobs.ashbyhq.com/finmid.com', 'Financial services with English-speaking finance positions', 'English Hiring Companies', 'active'),
('Finanztip', 'https://finanztip.jobs.personio.de/', 'Financial advice platform with English job openings', 'English Hiring Companies', 'active'),
('FICUS', 'https://ficushealth.jobs.personio.com/', 'Healthcare platform with English engineering and product roles', 'English Hiring Companies', 'active'),
('Finoa', 'https://finoa.jobs.personio.com/', 'Digital asset custody with English-speaking opportunities', 'English Hiring Companies', 'active'),
('FION Energy', 'https://www.linkedin.com/company/fion-energy/jobs/', 'Energy technology company with English job opportunities', 'English Hiring Companies', 'active'),
('goodcarbon', 'https://www.linkedin.com/company/goodcarbon/jobs/', 'Carbon management platform with English sales and service roles', 'English Hiring Companies', 'active'),
('GetYourGuide', 'https://www.getyourguide.careers/open-roles', 'Travel platform with international English job opportunities', 'English Hiring Companies', 'active'),
('gematik', 'https://www.gematik.de/stellenangebote/stellenangebote.html', 'Digital health infrastructure with English-speaking positions', 'English Hiring Companies', 'active'),
('JOIN', 'https://join.com/careers#openpositions', 'Recruitment platform with English job opportunities', 'English Hiring Companies', 'active'),
('Jungwild', 'https://jungwild.io/jobs/', 'Digital agency with English-speaking work environment', 'English Hiring Companies', 'active'),
('JustWatch', 'https://jobs.lever.co/justwatch', 'Movie streaming search with English job openings', 'English Hiring Companies', 'active'),
('ETERNO', 'https://careers.eterno.group/en/jobs', 'Business services group with English-speaking opportunities', 'English Hiring Companies', 'active'),
('KAIKO Systems', 'https://job-boards.eu.greenhouse.io/kaikosystems', 'Maritime technology with English job opportunities', 'English Hiring Companies', 'active'),
('KAYAK', 'https://www.kayak.com/careers/berlin/all', 'Travel search platform with English positions in Berlin', 'English Hiring Companies', 'active'),
('kertos', 'https://www.kertos.io/en/jobs', 'Data analytics platform with English job openings', 'English Hiring Companies', 'active'),
('kiron', 'https://www.kiron.ngo/careers#Positions', 'Educational nonprofit with English-speaking opportunities', 'English Hiring Companies', 'active'),
('kittl', 'https://jobs.ashbyhq.com/kittl', 'Design platform with English job opportunities', 'English Hiring Companies', 'active'),
('KNIME', 'https://knime.jobs.personio.de/', 'Data analytics platform with English-speaking positions', 'English Hiring Companies', 'active'),
('Knowunity', 'https://jobs.ashbyhq.com/knowunity', 'Educational platform with English job opportunities', 'English Hiring Companies', 'active'),
('Formo', 'https://eatformo.com/work/', 'Food technology company with English-speaking roles', 'English Hiring Companies', 'active'),
('Forto', 'https://careers.forto.com/forto-jobs/', 'Digital freight platform with English job opportunities', 'English Hiring Companies', 'active'),
('FREE NOW', 'https://job-boards.greenhouse.io/freenow', 'Mobility platform with English positions across Europe', 'English Hiring Companies', 'active'),
('Friendsurance', 'https://www.friendsurance.com/en/careers/', 'Digital insurance with English-speaking opportunities', 'English Hiring Companies', 'active'),
('FUNKE', 'https://karriere.funkemedien.de/de/', 'Media group with English job opportunities', 'English Hiring Companies', 'active'),
('LucaNet', 'https://www.lucanet.com/en/careers/jobs/', 'Financial software with English-speaking positions', 'English Hiring Companies', 'active'),
('Logistica OS', 'https://join.com/companies/logistica-oscom', 'Logistics platform with English job opportunities', 'English Hiring Companies', 'active'),
('Metiundo', 'https://jobs.metiundo.io/eng', 'Property technology with English-speaking roles', 'English Hiring Companies', 'active'),
('Merantix', 'https://careers.merantix.com/companies/deltia-2', 'AI venture studio with English job opportunities', 'English Hiring Companies', 'active'),
('Mercanis', 'https://mercanis.jobs.personio.de/', 'Supply chain platform with English-speaking positions', 'English Hiring Companies', 'active'),
('mgm-tp', 'https://jobs.mgm-tp.com/', 'Technology consulting with English job opportunities', 'English Hiring Companies', 'active'),
('Mindspace', 'https://www.mindspace.me/careers/', 'Coworking spaces with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Needle', 'https://needle.app/careers', 'Customer service platform with English sales and service roles', 'English Hiring Companies', 'active'),
('Peec AI', 'https://peec.ai/careers', 'AI technology company with English job opportunities', 'English Hiring Companies', 'active'),
('pplwise', 'https://pplwise.com/career/', 'HR analytics platform with English-speaking positions', 'English Hiring Companies', 'active'),
('ppro', 'https://www.ppro.com/about-us/careers/', 'Payment technology with English job opportunities', 'English Hiring Companies', 'active'),
('Purpose Green', 'https://purpose-green.jobs.personio.de/', 'Sustainable business solutions with English-speaking roles', 'English Hiring Companies', 'active');