-- Migration: Türkçeleştirme — recruitment_agencies tablosu
-- Kategori adları ve açıklamalar Türkçeye güncelleniyor

-- 1. Kategori adlarını güncelle
UPDATE recruitment_agencies SET category = 'İş Bulma Ajansları' WHERE category = 'Recruitment Agencies';
UPDATE recruitment_agencies SET category = 'İngilizce İşe Alan Şirketler' WHERE category = 'English Hiring Companies';

-- 2. Açıklamaları güncelle — İş Bulma Ajansları
UPDATE recruitment_agencies SET description = 'Üst düzey yönetici arama & İK danışmanlığı' WHERE name = 'DIA-AG';
UPDATE recruitment_agencies SET description = 'Küresel personel & geçici çalışan çözümleri' WHERE name = 'Randstad';
UPDATE recruitment_agencies SET description = 'İşgücü çözümleri & yetenek yerleştirme' WHERE name = 'ManpowerGroup';
UPDATE recruitment_agencies SET description = 'İş ilanları & kariyer portalı' WHERE name = 'JobBasel';
UPDATE recruitment_agencies SET description = 'Profesyonel & liderlik kadrosu işe alımı' WHERE name = 'Michael Page';
UPDATE recruitment_agencies SET description = 'Sektörler arası uzman işe alımı' WHERE name = 'Hays';
UPDATE recruitment_agencies SET description = 'Gi Group personel & İK hizmetleri' WHERE name = 'Gi Group';
UPDATE recruitment_agencies SET description = 'Junior & orta kademe yetenek yerleştirme' WHERE name = 'Page Personnel';
UPDATE recruitment_agencies SET description = 'Finans & hukuk işe alımı' WHERE name = 'Progress Professionals';
UPDATE recruitment_agencies SET description = 'Geçici & kalıcı işe alım' WHERE name = 'Adecco';
UPDATE recruitment_agencies SET description = 'Mühendislik & teknik personel' WHERE name = 'Brunel';
UPDATE recruitment_agencies SET description = 'Uzman düzeyinde profesyonel eşleştirme' WHERE name = 'Experts & Talents';
UPDATE recruitment_agencies SET description = 'Freelance & proje personeli' WHERE name = 'GULP';
UPDATE recruitment_agencies SET description = 'BT & dijital işe alım' WHERE name = 'Kontrast';
UPDATE recruitment_agencies SET description = 'Finans, idari & teknoloji pozisyonları' WHERE name = 'Robert Half';
UPDATE recruitment_agencies SET description = 'Esnek iş gücü & personel' WHERE name = 'Kelly Services';
UPDATE recruitment_agencies SET description = 'İK danışmanlığı & yetenek stratejisi' WHERE name = 'Engaged Company';
UPDATE recruitment_agencies SET description = 'Üst düzey yönetici arama & liderlik işe alımı' WHERE name = 'Frankfurt Fitch';
UPDATE recruitment_agencies SET description = 'Üst yönetim & yönetim kurulu araması' WHERE name = 'Ratbacher';
UPDATE recruitment_agencies SET description = 'Yönetici & uzman işe alımı' WHERE name = 'Optimise Search';
UPDATE recruitment_agencies SET description = 'Teknoloji & BT personeli' WHERE name = 'K Resources';
UPDATE recruitment_agencies SET description = 'İskandinav-Alman akademik & profesyonel pozisyonlar' WHERE name = 'Academic Work';
UPDATE recruitment_agencies SET description = 'BT & yazılım iş platformu' WHERE name = 'get-in-IT';
UPDATE recruitment_agencies SET description = 'Uluslararası profesyonel işe alım' WHERE name = 'Robert Walters';
UPDATE recruitment_agencies SET description = 'SAP & BT danışmanlık personeli' WHERE name = 'SHREE';
UPDATE recruitment_agencies SET description = 'Teknoloji & dijital yetenek eşleştirme' WHERE name = 'WeMatch';
UPDATE recruitment_agencies SET description = 'Geçici yönetim & İK danışmanlığı' WHERE name = 'TA Management';
UPDATE recruitment_agencies SET description = 'Çok sektörlü işe alım ajansı' WHERE name = 'Grafton';
UPDATE recruitment_agencies SET description = 'BT & proje personeli' WHERE name = '4 Chill Consulting';
UPDATE recruitment_agencies SET description = 'Yönetici & liderlik araması' WHERE name = 'HeadMatch';
UPDATE recruitment_agencies SET description = 'Sağlık & tıbbi işe alım' WHERE name = 'IHH Healthcare';
UPDATE recruitment_agencies SET description = 'Uluslararası İK & yetenek çözümleri' WHERE name = 'Solua';
UPDATE recruitment_agencies SET description = 'Kalıcı teknoloji & finans pozisyonları' WHERE name = 'Perm4';
UPDATE recruitment_agencies SET description = 'Yaşam bilimleri & ilaç personeli' WHERE name = 'Vires Consulting';
UPDATE recruitment_agencies SET description = 'Yönetici arama & İK danışmanlığı' WHERE name = 'Skallbach';
UPDATE recruitment_agencies SET description = 'BT & girişim teknolojisi işe alımı' WHERE name = 'TechPunk';
UPDATE recruitment_agencies SET description = 'SAP uzmanı işe alımı' WHERE name = 'Ignite SAP';
UPDATE recruitment_agencies SET description = 'Küresel uzman işe alım firması' WHERE name = 'Antal International';
UPDATE recruitment_agencies SET description = 'Mühendislik & enerji personeli' WHERE name = 'Progressive Recruitment';
UPDATE recruitment_agencies SET description = 'Yönetici arama & liderlik danışmanlığı' WHERE name = 'ISG';
UPDATE recruitment_agencies SET description = 'Teknoloji & dijital işe alım' WHERE name = 'Linking Talents';
UPDATE recruitment_agencies SET description = 'Teknoloji & siber güvenlik personeli' WHERE name = 'Noir Consulting';
UPDATE recruitment_agencies SET description = 'Yönetici & yönetim kurulu düzeyinde arama' WHERE name = 'Amore Bond';
UPDATE recruitment_agencies SET description = 'İki dilli & uluslararası personel' WHERE name = 'Ital Staffing';
UPDATE recruitment_agencies SET description = 'Enerji & sürdürülebilirlik pozisyonları' WHERE name = 'Green Recruitment Company';
UPDATE recruitment_agencies SET description = 'Salesforce & bulut uzmanları' WHERE name = 'Mason Frank';
UPDATE recruitment_agencies SET description = 'Dijital & yaratıcı yetenek' WHERE name = 'Coamos';
UPDATE recruitment_agencies SET description = 'Teknoloji & dönüşüm personeli' WHERE name = 'OXIN';
UPDATE recruitment_agencies SET description = 'Yaratıcı & tasarım işe alımı' WHERE name = 'Design Deck';
UPDATE recruitment_agencies SET description = 'Finans & risk profesyonelleri' WHERE name = 'Goodman Masson';
UPDATE recruitment_agencies SET description = 'Enerji & mühendislik uzmanları' WHERE name = 'G2 Recruitment';
UPDATE recruitment_agencies SET description = 'Geçici & proje personeli' WHERE name = 'Radial Bud';
UPDATE recruitment_agencies SET description = 'Liderlik değerlendirme & arama' WHERE name = 'Mercuri Urval';
UPDATE recruitment_agencies SET description = 'İK teknolojisi & yetenek platformu' WHERE name = 'Emplion';
UPDATE recruitment_agencies SET description = 'Personel & yönetim çözümleri' WHERE name = 'PMS';
UPDATE recruitment_agencies SET description = 'Satış, pazarlama & finans pozisyonları' WHERE name = 'LEW Group';
UPDATE recruitment_agencies SET description = 'Dijital dönüşüm & BT işe alımı' WHERE name = 'Valiy One';
UPDATE recruitment_agencies SET description = 'Finans & profesyonel hizmetler' WHERE name = 'Morgan McKinley';
UPDATE recruitment_agencies SET description = 'Yaşam bilimleri & medikal teknoloji yeteneği' WHERE name = 'Aventis Group';
UPDATE recruitment_agencies SET description = 'Teknoloji & veri uzmanları' WHERE name = 'Darwin Recruitment';
UPDATE recruitment_agencies SET description = 'Uluslararası yönetici araması' WHERE name = 'Zabel Global';
UPDATE recruitment_agencies SET description = 'C seviyesi & yönetim kurulu işe alımı' WHERE name = 'Page Executive';
UPDATE recruitment_agencies SET description = 'Dijital & BT personeli' WHERE name = 'HIT Consulting';
UPDATE recruitment_agencies SET description = 'Finans & geçici yönetim' WHERE name = 'Aristo Group';
UPDATE recruitment_agencies SET description = 'Teknoloji & proje işe alımı' WHERE name = 'SGEN CIS';
UPDATE recruitment_agencies SET description = 'Malta merkezli küresel personel' WHERE name = 'Konnekt';
UPDATE recruitment_agencies SET description = 'Yarı iletken & elektronik personeli' WHERE name = 'IC Resources';
UPDATE recruitment_agencies SET description = 'İK teknolojisi & iş eşleştirme' WHERE name = 'Kooku';
UPDATE recruitment_agencies SET description = 'Yenilenebilir enerji işe alımı' WHERE name = 'Taylor Hopkinson';
UPDATE recruitment_agencies SET description = 'Teknoloji & dönüşüm pozisyonları' WHERE name = 'Trans Personal Group';
UPDATE recruitment_agencies SET description = 'Orta Avrupa BT personeli' WHERE name = 'ALSES';
UPDATE recruitment_agencies SET description = 'Finans & fintech yeteneği' WHERE name = 'Xelentia';
UPDATE recruitment_agencies SET description = 'Siber güvenlik & BT personeli' WHERE name = 'Evolutionary Cyber Solutions';
UPDATE recruitment_agencies SET description = 'BİT & altyapı uzmanları' WHERE name = 'Precision ICT';
UPDATE recruitment_agencies SET description = 'Medya & basın personeli' WHERE name = 'Press Link Services';
UPDATE recruitment_agencies SET description = 'ABD-Alman iki dilli işe alım' WHERE name = 'Locke Staffing';
UPDATE recruitment_agencies SET description = 'Teknoloji, dijital & liderlik pozisyonları' WHERE name = 'Harvey Nash';
UPDATE recruitment_agencies SET description = 'Çok dilli & AB personeli' WHERE name = 'Approach People';
UPDATE recruitment_agencies SET description = 'İK inovasyonu & yetenek' WHERE name = 'Recruiting Evolution';
UPDATE recruitment_agencies SET description = 'UI/UX & tasarım yeteneği' WHERE name = 'UI Staffing';
UPDATE recruitment_agencies SET description = 'Teknoloji & mühendislik personeli' WHERE name = 'Senasis Group';
UPDATE recruitment_agencies SET description = 'Teknoloji & girişim işe alımı' WHERE name = 'IQ Talent Partners';
UPDATE recruitment_agencies SET description = 'Küresel iki dilli işe alım' WHERE name = 'Discover International';
UPDATE recruitment_agencies SET description = 'Geçici & serbest uzmanlar' WHERE name = 'Etengo';
UPDATE recruitment_agencies SET description = 'Çok dilli Avrupa iş portalı' WHERE name = 'Euro Job Consult';
UPDATE recruitment_agencies SET description = 'Satış & pazarlama personeli' WHERE name = 'M2 Talents';
UPDATE recruitment_agencies SET description = 'Veri bilimi & analitik pozisyonları' WHERE name = 'Data Talent';
UPDATE recruitment_agencies SET description = 'Yönetici & finans araması' WHERE name = 'Brink Holding';
UPDATE recruitment_agencies SET description = 'İşe alım süreci dış kaynak kullanımı' WHERE name = 'Opus RS';
UPDATE recruitment_agencies SET description = 'İK danışmanlığı & yerleştirme' WHERE name = 'Alpha Consult Gruppe';
UPDATE recruitment_agencies SET description = 'Yönetici & niş işe alım' WHERE name = 'Search Talent';
UPDATE recruitment_agencies SET description = 'Finans & hukuk personeli' WHERE name = 'LP Associates';
UPDATE recruitment_agencies SET description = 'ABD-Alman yönetici araması' WHERE name = 'Hardenberg Group';
UPDATE recruitment_agencies SET description = 'BT & teknoloji personeli' WHERE name = 'IT Workforce';
UPDATE recruitment_agencies SET description = 'İK & geçici yönetim' WHERE name = 'Schulmeister Consulting';
UPDATE recruitment_agencies SET description = 'Nitelikli meslek & teknoloji pozisyonları' WHERE name = 'Skill Recruit';
UPDATE recruitment_agencies SET description = 'İsviçre-Alman finans işe alımı' WHERE name = 'Division One';
UPDATE recruitment_agencies SET description = 'Küresel yetenek çözümleri' WHERE name = 'JAC Group';
UPDATE recruitment_agencies SET description = 'Yaratıcı & dijital personel' WHERE name = 'TON HR Evolution';
UPDATE recruitment_agencies SET description = 'Yönetici & uzman eşleştirme' WHERE name = 'Expert Scout';
UPDATE recruitment_agencies SET description = 'Teknoloji & mühendislik pozisyonları' WHERE name = 'K Recruiting';
UPDATE recruitment_agencies SET description = 'Geleceğe yönelik yetenek çözümleri' WHERE name = 'Future Select Consult';
UPDATE recruitment_agencies SET description = 'Hukuk & uyum işe alımı' WHERE name = 'LRC';
UPDATE recruitment_agencies SET description = 'Kalite & mevzuat uyum personeli' WHERE name = 'TheQS Consulting';
UPDATE recruitment_agencies SET description = 'Teknoloji & dönüşüm işe alımı' WHERE name = 'Constares';
UPDATE recruitment_agencies SET description = 'Satış & pazarlama yeteneği' WHERE name = 'Market Expanded';
UPDATE recruitment_agencies SET description = 'Yönetici & liderlik araması' WHERE name = 'Klug Executive Search';
UPDATE recruitment_agencies SET description = 'Bireysel & ev personeli' WHERE name = 'Private Personal';
UPDATE recruitment_agencies SET description = 'Küresel yönetici araması' WHERE name = 'Morgan Philips';
UPDATE recruitment_agencies SET description = 'Enerji & altyapı pozisyonları' WHERE name = 'Spencer Ogden';
UPDATE recruitment_agencies SET description = 'Teknoloji & dijital personel' WHERE name = 'Skills Alliance';
UPDATE recruitment_agencies SET description = 'Küresel işe alım çözümleri' WHERE name = 'SCRO Global';
UPDATE recruitment_agencies SET description = 'BT & ağ uzmanları' WHERE name = 'eBlue Net';
UPDATE recruitment_agencies SET description = 'İki dilli & uluslararası personel' WHERE name = 'DA Connection';
UPDATE recruitment_agencies SET description = 'Yönetici & geçici liderlik' WHERE name = 'Optimize Exe';
UPDATE recruitment_agencies SET description = 'Teknoloji & sağlık personeli' WHERE name = 'Veredus Consulting';
UPDATE recruitment_agencies SET description = 'Genel İK & personel' WHERE name = 'HR Recruitment';
UPDATE recruitment_agencies SET description = 'İş & İK danışmanlığı' WHERE name = 'Intention Business';
UPDATE recruitment_agencies SET description = 'Dijital & yaratıcı yetenek' WHERE name = 'Digital Waffle';
UPDATE recruitment_agencies SET description = 'Kişiselleştirilmiş iş eşleştirme' WHERE name = 'WeMe';
UPDATE recruitment_agencies SET description = 'Teknoloji & girişim işe alımı' WHERE name = 'One Hiring';
UPDATE recruitment_agencies SET description = 'BT & proje personeli' WHERE name = 'Quantum Consultancy';
UPDATE recruitment_agencies SET description = 'Profesyonel & dernek pozisyonları' WHERE name = 'Progress Association';
UPDATE recruitment_agencies SET description = 'E-ticaret & lojistik personeli' WHERE name = 'Pack TM';
UPDATE recruitment_agencies SET description = 'Teknoloji & dönüşüm pozisyonları' WHERE name = 'Evolve Ltd';
UPDATE recruitment_agencies SET description = 'Kariyer koçluğu & iş ilanları' WHERE name = 'Career Factory';
UPDATE recruitment_agencies SET description = 'Tıbbi & sağlık personeli' WHERE name = 'Medicopec';
UPDATE recruitment_agencies SET description = 'Dijital & oyun yeteneği' WHERE name = 'NXT Hero';
UPDATE recruitment_agencies SET description = 'Yaratıcı & pazarlama personeli' WHERE name = 'Intelligent People';
UPDATE recruitment_agencies SET description = 'Teknoloji & dijital işe alım' WHERE name = 'Evolve Talent';
UPDATE recruitment_agencies SET description = 'BT iş ilanları platformu' WHERE name = 'ITS Jobs We R Online';
UPDATE recruitment_agencies SET description = 'İdari & destek personeli' WHERE name = 'Joanne Hart';
UPDATE recruitment_agencies SET description = 'Teknoloji & niş pozisyonlar' WHERE name = 'Rizer Recruitment';
UPDATE recruitment_agencies SET description = 'İK & geçici danışmanlık' WHERE name = 'Consultason';
UPDATE recruitment_agencies SET description = 'BT & yazılım uzmanları' WHERE name = 'Infotech Recruitment';
UPDATE recruitment_agencies SET description = 'Almanca konuşan teknoloji personeli' WHERE name = 'Makk Rohr';
UPDATE recruitment_agencies SET description = 'BT & dijital dış kaynak kullanımı' WHERE name = 'Viru Sourcing';
UPDATE recruitment_agencies SET description = 'Yönetici & İK danışmanlığı' WHERE name = 'Hiber Roy Consultants';
UPDATE recruitment_agencies SET description = 'Tıbbi & yaşam bilimleri' WHERE name = 'Medipoint';
UPDATE recruitment_agencies SET description = 'İK & liderlik danışmanlığı' WHERE name = 'Essmann Beratung';
UPDATE recruitment_agencies SET description = 'Enerji & mühendislik personeli' WHERE name = 'ERSG Global';
UPDATE recruitment_agencies SET description = 'Teknik & mühendislik pozisyonları' WHERE name = 'ISIS Technical';
UPDATE recruitment_agencies SET description = 'BT & mühendislik personeli' WHERE name = 'Fortech Consulting';
UPDATE recruitment_agencies SET description = 'Yetenek kazanım platformu' WHERE name = 'Talentania';
UPDATE recruitment_agencies SET description = 'Satış, pazarlama & teknoloji işleri' WHERE name = 'Career People';
UPDATE recruitment_agencies SET description = 'Küresel teknoloji işe alımı' WHERE name = 'Tech Global';
UPDATE recruitment_agencies SET description = 'Yönetici & uzman araması' WHERE name = 'Pantheon Recruitment';
UPDATE recruitment_agencies SET description = 'Hollanda-Alman BT personeli' WHERE name = 'Spartacus IT';
UPDATE recruitment_agencies SET description = 'Yapay zeka destekli iş eşleştirme' WHERE name = 'MaxMatch';
UPDATE recruitment_agencies SET description = 'Teknoloji & dijital yetenek' WHERE name = 'Zync Group';

-- 3. Açıklamaları güncelle — İngilizce İşe Alan Şirketler
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan e-ticaret moda platformu' WHERE name = 'About You';
UPDATE recruitment_agencies SET description = 'Berlin''de İngilizce konuşulan pozisyonlar sunan küresel danışmanlık firması' WHERE name = 'Accenture';
UPDATE recruitment_agencies SET description = 'İngilizce iş ilanları sunan finans hizmetleri girişimi' WHERE name = 'Accountable';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan yapay zeka destekli platform' WHERE name = 'Acemate.ai';
UPDATE recruitment_agencies SET description = 'Uluslararası ekip fırsatları sunan dil öğrenme platformu' WHERE name = 'Babbel';
UPDATE recruitment_agencies SET description = 'İngilizce çalışma ortamına sahip İK yazılım şirketi' WHERE name = 'Personio';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan fintech girişimi' WHERE name = 'Banxware';
UPDATE recruitment_agencies SET description = 'Uluslararası İngilizce pozisyonlara sahip kimya sektörü lideri' WHERE name = 'BASF';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan fırsatlar sunan yönetim danışmanlığı' WHERE name = 'BearingPoint';
UPDATE recruitment_agencies SET description = 'İngilizce iş açıklamaları sunan lojistik optimizasyon platformu' WHERE name = 'Bettermile';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan karbon yönetimi girişimi' WHERE name = 'Carbon One';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan yapay zeka teknoloji şirketi' WHERE name = 'Caidera';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip temiz enerji platformu' WHERE name = 'Calima';
UPDATE recruitment_agencies SET description = 'Uluslararası İngilizce iş fırsatları sunan tasarım platformu' WHERE name = 'Canva';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan sağlık alanında yapay zeka şirketi' WHERE name = 'Caresyntax';
UPDATE recruitment_agencies SET description = 'İngilizce iş ilanları sunan temiz teknoloji girişimi' WHERE name = 'Cloover';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan dijital asistan platformu' WHERE name = 'Claire';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan e-öğrenim platformu' WHERE name = 'Elearnio';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan finans pozisyonlarına sahip finans hizmetleri' WHERE name = 'Finmid';
UPDATE recruitment_agencies SET description = 'İngilizce iş ilanları sunan finansal tavsiye platformu' WHERE name = 'Finanztip';
UPDATE recruitment_agencies SET description = 'İngilizce mühendislik ve ürün pozisyonlarına sahip sağlık platformu' WHERE name = 'FICUS';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan dijital varlık saklama hizmeti' WHERE name = 'Finoa';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan enerji teknolojisi şirketi' WHERE name = 'FION Energy';
UPDATE recruitment_agencies SET description = 'İngilizce satış ve hizmet pozisyonlarına sahip karbon yönetimi platformu' WHERE name = 'goodcarbon';
UPDATE recruitment_agencies SET description = 'Uluslararası İngilizce iş fırsatları sunan seyahat platformu' WHERE name = 'GetYourGuide';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip dijital sağlık altyapısı' WHERE name = 'gematik';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan işe alım platformu' WHERE name = 'JOIN';
UPDATE recruitment_agencies SET description = 'İngilizce çalışma ortamına sahip dijital ajans' WHERE name = 'Jungwild';
UPDATE recruitment_agencies SET description = 'İngilizce iş ilanları sunan film akış arama platformu' WHERE name = 'JustWatch';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan iş hizmetleri grubu' WHERE name = 'ETERNO';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan denizcilik teknolojisi şirketi' WHERE name = 'KAIKO Systems';
UPDATE recruitment_agencies SET description = 'Berlin''de İngilizce pozisyonlara sahip seyahat arama platformu' WHERE name = 'KAYAK';
UPDATE recruitment_agencies SET description = 'İngilizce iş ilanları sunan veri analitiği platformu' WHERE name = 'kertos';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan eğitim odaklı kar amacı gütmeyen kuruluş' WHERE name = 'kiron';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan tasarım platformu' WHERE name = 'kittl';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip veri analitiği platformu' WHERE name = 'KNIME';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan eğitim platformu' WHERE name = 'Knowunity';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan gıda teknolojisi şirketi' WHERE name = 'Formo';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan dijital kargo platformu' WHERE name = 'Forto';
UPDATE recruitment_agencies SET description = 'Avrupa genelinde İngilizce pozisyonlara sahip mobilite platformu' WHERE name = 'FREE NOW';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan dijital sigorta şirketi' WHERE name = 'Friendsurance';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan medya grubu' WHERE name = 'FUNKE';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip finansal yazılım şirketi' WHERE name = 'LucaNet';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan lojistik platformu' WHERE name = 'Logistica OS';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan gayrimenkul teknolojisi şirketi' WHERE name = 'Metiundo';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan yapay zeka girişim stüdyosu' WHERE name = 'Merantix';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip tedarik zinciri platformu' WHERE name = 'Mercanis';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan teknoloji danışmanlık firması' WHERE name = 'mgm-tp';
UPDATE recruitment_agencies SET description = 'İngilizce fırsatlar sunan ortak çalışma alanları' WHERE name = 'Mindspace';
UPDATE recruitment_agencies SET description = 'İngilizce satış ve hizmet pozisyonlarına sahip müşteri hizmetleri platformu' WHERE name = 'Needle';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan yapay zeka teknoloji şirketi' WHERE name = 'Peec AI';
UPDATE recruitment_agencies SET description = 'İngilizce konuşulan pozisyonlara sahip İK analitiği platformu' WHERE name = 'pplwise';
UPDATE recruitment_agencies SET description = 'İngilizce iş fırsatları sunan ödeme teknolojisi şirketi' WHERE name = 'ppro';
UPDATE recruitment_agencies SET description = 'İngilizce pozisyonlar sunan sürdürülebilir iş çözümleri şirketi' WHERE name = 'Purpose Green';
