-- Create recruitment_agencies table
CREATE TABLE recruitment_agencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_recruitment_agencies_status ON recruitment_agencies(status);
CREATE INDEX idx_recruitment_agencies_category ON recruitment_agencies(category);
CREATE INDEX idx_recruitment_agencies_created_at ON recruitment_agencies(created_at DESC);

-- Add RLS (Row Level Security)
ALTER TABLE recruitment_agencies ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "recruitment_agencies_select_all" ON recruitment_agencies
  FOR SELECT USING (true);

-- Insert initial data from constants (150 agencies)
INSERT INTO recruitment_agencies (name, url, description, category, status) VALUES
('DIA-AG', 'https://dia-ag.com', 'Executive search & HR consulting', 'Recruitment Agencies', 'active'),
('Randstad', 'https://randstad.de', 'Global staffing & temp solutions', 'Recruitment Agencies', 'active'),
('ManpowerGroup', 'https://manpower.de', 'Workforce solutions & talent placement', 'Recruitment Agencies', 'active'),
('JobBasel', 'https://jobbasel.com', 'Job board & career portal', 'Recruitment Agencies', 'active'),
('Michael Page', 'https://michaelpage.de', 'Professional & leadership recruitment', 'Recruitment Agencies', 'active'),
('Hays', 'https://hays.de', 'Specialist recruitment across industries', 'Recruitment Agencies', 'active'),
('Gi Group', 'https://de.gigroup.com', 'Gi Group staffing & HR services', 'Recruitment Agencies', 'active'),
('Page Personnel', 'https://pagepersonnel.de', 'Junior & mid-level talent placement', 'Recruitment Agencies', 'active'),
('Progress Professionals', 'https://progressprofessionals.de', 'Finance & legal recruitment', 'Recruitment Agencies', 'active'),
('Adecco', 'https://adecco.de', 'Temporary & permanent hiring', 'Recruitment Agencies', 'active'),
('Brunel', 'https://brunel.net/de-de', 'Engineering & technical staffing', 'Recruitment Agencies', 'active'),
('Experts & Talents', 'https://experts-talents.de', 'Expert-level professional matching', 'Recruitment Agencies', 'active'),
('GULP', 'https://gulp.de', 'Freelancer & project staffing', 'Recruitment Agencies', 'active'),
('Kontrast', 'https://kontrast-gmbh.de', 'IT & digital recruitment', 'Recruitment Agencies', 'active'),
('Robert Half', 'https://roberthalf.com/de', 'Finance, admin & tech roles', 'Recruitment Agencies', 'active'),
('Kelly Services', 'https://kelly-services.de', 'Flexible workforce & staffing', 'Recruitment Agencies', 'active'),
('Engaged Company', 'https://engaged-company.com', 'HR consulting & talent strategy', 'Recruitment Agencies', 'active'),
('Frankfurt Fitch', 'https://frankfurtfitch.com/de', 'Executive search & leadership hiring', 'Recruitment Agencies', 'active'),
('Ratbacher', 'https://ratbacher.de', 'Senior management & board search', 'Recruitment Agencies', 'active'),
('Optimise Search', 'https://optimisesearch.com', 'Executive & specialist recruitment', 'Recruitment Agencies', 'active'),
('K Resources', 'https://kresources.com', 'Tech & IT staffing', 'Recruitment Agencies', 'active'),
('Academic Work', 'https://academicwork.de', 'Nordic-German academic & professional roles', 'Recruitment Agencies', 'active'),
('get-in-IT', 'https://get-in-it.de', 'IT & software job platform', 'Recruitment Agencies', 'active'),
('Robert Walters', 'https://robertwalters.de', 'International professional recruitment', 'Recruitment Agencies', 'active'),
('SHREE', 'https://shree.com/de-de', 'SAP & IT consulting staffing', 'Recruitment Agencies', 'active'),
('WeMatch', 'https://wematch.de', 'Tech & digital talent matching', 'Recruitment Agencies', 'active'),
('TA Management', 'https://ta-management.de', 'Interim management & HR consulting', 'Recruitment Agencies', 'active'),
('Grafton', 'https://de.grafton.com', 'Multisector recruitment agency', 'Recruitment Agencies', 'active'),
('4 Chill Consulting', 'https://4chillconsulting.de', 'IT & project staffing', 'Recruitment Agencies', 'active'),
('HeadMatch', 'https://headmatch.de', 'Executive & leadership search', 'Recruitment Agencies', 'active'),
('IHH Healthcare', 'https://ihh.com/de', 'Healthcare & medical recruitment', 'Recruitment Agencies', 'active'),
('Solua', 'https://solua.com', 'International HR & talent solutions', 'Recruitment Agencies', 'active'),
('Perm4', 'https://perm4.com', 'Permanent tech & finance roles', 'Recruitment Agencies', 'active'),
('Vires Consulting', 'https://viresconsulting.com', 'Life sciences & pharma staffing', 'Recruitment Agencies', 'active'),
('Skallbach', 'https://skallbach.de', 'Executive search & HR advisory', 'Recruitment Agencies', 'active'),
('TechPunk', 'https://techpunk.com', 'IT & startup tech hiring', 'Recruitment Agencies', 'active'),
('Ignite SAP', 'https://ignitesap.com', 'SAP specialist recruitment', 'Recruitment Agencies', 'active'),
('Antal International', 'https://antal.com', 'Global specialist recruitment firm', 'Recruitment Agencies', 'active'),
('Progressive Recruitment', 'https://progressive-recruitment.de', 'Engineering & energy staffing', 'Recruitment Agencies', 'active'),
('ISG', 'https://isg.com/de', 'Executive search & leadership advisory', 'Recruitment Agencies', 'active'),
('Linking Talents', 'https://linkingtalents.de', 'Tech & digital recruitment', 'Recruitment Agencies', 'active'),
('Noir Consulting', 'https://noirconsulting.co.uk', 'Tech & cybersecurity staffing', 'Recruitment Agencies', 'active'),
('Amore Bond', 'https://amorebond.com/de', 'Executive & board-level search', 'Recruitment Agencies', 'active'),
('Ital Staffing', 'https://italstaffing.com/de-de', 'Bilingual & international staffing', 'Recruitment Agencies', 'active'),
('Green Recruitment Company', 'https://greenrecruitmentcompany.com', 'Energy & sustainability roles', 'Recruitment Agencies', 'active'),
('Mason Frank', 'https://masonfrank.com', 'Salesforce & cloud specialists', 'Recruitment Agencies', 'active'),
('Coamos', 'https://coamos.de', 'Digital & creative talent', 'Recruitment Agencies', 'active'),
('OXIN', 'https://weareoxin.com', 'Tech & transformation staffing', 'Recruitment Agencies', 'active'),
('Design Deck', 'https://designdeck.com', 'Creative & design recruitment', 'Recruitment Agencies', 'active'),
('Goodman Masson', 'https://goodmanmasson.de', 'Finance & risk professionals', 'Recruitment Agencies', 'active'),
('G2 Recruitment', 'https://g2recruitment.com', 'Energy & engineering specialists', 'Recruitment Agencies', 'active'),
('Radial Bud', 'https://radialbud.de', 'Interim & project staffing', 'Recruitment Agencies', 'active'),
('Mercuri Urval', 'https://mercuriurval.com/de-de', 'Leadership assessment & search', 'Recruitment Agencies', 'active'),
('Emplion', 'https://emplion.de', 'HR tech & talent platform', 'Recruitment Agencies', 'active'),
('PMS', 'https://pms.de', 'Personnel & management solutions', 'Recruitment Agencies', 'active'),
('LEW Group', 'https://lewgroup.com', 'Sales, marketing & finance roles', 'Recruitment Agencies', 'active'),
('Valiy One', 'https://valiyone.com', 'Digital transformation & IT hiring', 'Recruitment Agencies', 'active'),
('Morgan McKinley', 'https://de.morganmckinley.com', 'Finance & professional services', 'Recruitment Agencies', 'active'),
('Aventis Group', 'https://aventisgroup.com', 'Life sciences & medtech talent', 'Recruitment Agencies', 'active'),
('Darwin Recruitment', 'https://darwinrecruitment.com', 'Tech & data specialists', 'Recruitment Agencies', 'active'),
('Zabel Global', 'https://zabelglobal.com', 'International executive search', 'Recruitment Agencies', 'active'),
('Page Executive', 'https://pageexecutive.com', 'C-level & board recruitment', 'Recruitment Agencies', 'active'),
('HIT Consulting', 'https://wearehitconsulting.com', 'Digital & IT staffing', 'Recruitment Agencies', 'active'),
('Aristo Group', 'https://aristo-group.com', 'Finance & interim management', 'Recruitment Agencies', 'active'),
('SGEN CIS', 'https://sgencis.de', 'Tech & project recruitment', 'Recruitment Agencies', 'active'),
('Konnekt', 'https://konnekt.net', 'Malta-based, global staffing', 'Recruitment Agencies', 'active'),
('IC Resources', 'https://ic-resources.com/de', 'Semiconductor & electronics staffing', 'Recruitment Agencies', 'active'),
('Kooku', 'https://kooku.de', 'HR tech & job matching', 'Recruitment Agencies', 'active'),
('Taylor Hopkinson', 'https://taylorhopkinson.com', 'Renewable energy recruitment', 'Recruitment Agencies', 'active'),
('Trans Personal Group', 'https://transpersonalgroup.co.uk', 'Tech & transformation roles', 'Recruitment Agencies', 'active'),
('ALSES', 'https://alses.sk', 'Central European IT staffing', 'Recruitment Agencies', 'active'),
('Xelentia', 'https://xelentia.com', 'Finance & fintech talent', 'Recruitment Agencies', 'active'),
('Evolutionary Cyber Solutions', 'https://evolutionarycybersolutions.com', 'Cybersecurity & IT staffing', 'Recruitment Agencies', 'active'),
('Precision ICT', 'https://precisionict.com', 'ICT & infrastructure specialists', 'Recruitment Agencies', 'active'),
('Press Link Services', 'https://presslinkservices.com', 'Media & press staffing', 'Recruitment Agencies', 'active'),
('Locke Staffing', 'https://locke-staffing.com', 'US-German bilingual recruitment', 'Recruitment Agencies', 'active'),
('Harvey Nash', 'https://harveynash.de', 'Tech, digital & leadership roles', 'Recruitment Agencies', 'active'),
('Approach People', 'https://approachpeople.com', 'Multilingual & EU staffing', 'Recruitment Agencies', 'active'),
('Recruiting Evolution', 'https://recruitingevolution.de', 'HR innovation & talent', 'Recruitment Agencies', 'active'),
('UI Staffing', 'https://uistaffing.de', 'UI/UX & design talent', 'Recruitment Agencies', 'active'),
('Senasis Group', 'https://senasis.group.de', 'Tech & engineering staffing', 'Recruitment Agencies', 'active'),
('IQ Talent Partners', 'https://iqtalentpartners.com', 'Tech & startup recruitment', 'Recruitment Agencies', 'active'),
('Discover International', 'https://discoverinternational.com', 'Global bilingual recruitment', 'Recruitment Agencies', 'active'),
('Etengo', 'https://etengo.de', 'Interim & freelance experts', 'Recruitment Agencies', 'active'),
('Euro Job Consult', 'https://eurojobconsult.com', 'Multilingual European job portal', 'Recruitment Agencies', 'active'),
('M2 Talents', 'https://m2talents.com', 'Sales & marketing staffing', 'Recruitment Agencies', 'active'),
('Data Talent', 'https://data-talent.de', 'Data science & analytics roles', 'Recruitment Agencies', 'active'),
('Brink Holding', 'https://brink-holding.com', 'Executive & finance search', 'Recruitment Agencies', 'active'),
('Opus RS', 'https://opusrs.com', 'Recruitment process outsourcing', 'Recruitment Agencies', 'active'),
('Alpha Consult Gruppe', 'https://alphaconsultgruppe.org', 'HR consulting & placement', 'Recruitment Agencies', 'active'),
('Search Talent', 'https://searchtalent.de', 'Executive & niche recruitment', 'Recruitment Agencies', 'active'),
('LP Associates', 'https://lpassociates.com', 'Finance & legal staffing', 'Recruitment Agencies', 'active'),
('Hardenberg Group', 'https://hardenberegroupllc.com', 'US-German executive search', 'Recruitment Agencies', 'active'),
('IT Workforce', 'https://itworkforce.de', 'IT & tech staffing', 'Recruitment Agencies', 'active'),
('Schulmeister Consulting', 'https://schulmeistereconsulting.com/de', 'HR & interim management', 'Recruitment Agencies', 'active'),
('Skill Recruit', 'https://skillrecruit.com', 'Skilled trades & tech roles', 'Recruitment Agencies', 'active'),
('Division One', 'https://division-one.ch', 'Swiss-German finance recruitment', 'Recruitment Agencies', 'active'),
('JAC Group', 'https://jacgroup.com', 'Global talent solutions', 'Recruitment Agencies', 'active'),
('TON HR Evolution', 'https://tonhrevolution.com', 'Creative & digital staffing', 'Recruitment Agencies', 'active'),
('Expert Scout', 'https://expertscout.com', 'Executive & expert matching', 'Recruitment Agencies', 'active'),
('K Recruiting', 'https://k-recruiting.com', 'Tech & engineering roles', 'Recruitment Agencies', 'active'),
('Future Select Consult', 'https://futureselectconsult.de', 'Future-focused talent solutions', 'Recruitment Agencies', 'active'),
('LRC', 'https://lrcgmbh.de', 'Legal & compliance recruitment', 'Recruitment Agencies', 'active'),
('TheQS Consulting', 'https://theqs-consulting.de', 'Quality & regulatory staffing', 'Recruitment Agencies', 'active'),
('Constares', 'https://constares.de', 'Tech & transformation hiring', 'Recruitment Agencies', 'active'),
('Market Expanded', 'https://marketexpanded.de', 'Sales & marketing talent', 'Recruitment Agencies', 'active'),
('Klug Executive Search', 'https://klug-executivesearch.de', 'Executive & leadership search', 'Recruitment Agencies', 'active'),
('Private Personal', 'https://privatepersonal.de', 'Personal & household staffing', 'Recruitment Agencies', 'active'),
('Morgan Philips', 'https://morganphilips.com', 'Global executive search', 'Recruitment Agencies', 'active'),
('Spencer Ogden', 'https://spencer-ogden.com', 'Energy & infrastructure roles', 'Recruitment Agencies', 'active'),
('Skills Alliance', 'https://skillsalliance.com', 'Tech & digital staffing', 'Recruitment Agencies', 'active'),
('SCRO Global', 'https://scroglobbal.com', 'Global recruitment solutions', 'Recruitment Agencies', 'active'),
('eBlue Net', 'https://eblue-net.de', 'IT & network specialists', 'Recruitment Agencies', 'active'),
('DA Connection', 'https://daconnection.de', 'Bilingual & international staffing', 'Recruitment Agencies', 'active'),
('Optimize Exe', 'https://optimizeexe.com', 'Executive & interim leadership', 'Recruitment Agencies', 'active'),
('Veredus Consulting', 'https://veredusconsulting.com', 'Tech & healthcare staffing', 'Recruitment Agencies', 'active'),
('HR Recruitment', 'https://hr-recruitment.de', 'General HR & staffing', 'Recruitment Agencies', 'active'),
('Intention Business', 'https://intentionbusiness.com', 'Business & HR consulting', 'Recruitment Agencies', 'active'),
('Digital Waffle', 'https://digitalwaffle.co.uk', 'Digital & creative talent', 'Recruitment Agencies', 'active'),
('WeMe', 'https://weme.de', 'Personalized job matching', 'Recruitment Agencies', 'active'),
('One Hiring', 'https://onehiring.com/de', 'Tech & startup recruitment', 'Recruitment Agencies', 'active'),
('Quantum Consultancy', 'https://quantum-consultancy.com', 'IT & project staffing', 'Recruitment Agencies', 'active'),
('Progress Association', 'https://progressassociation.de', 'Professional & association roles', 'Recruitment Agencies', 'active'),
('Pack TM', 'https://packtm.com', 'E-commerce & logistics staffing', 'Recruitment Agencies', 'active'),
('Evolve Ltd', 'https://evolve-ltd.co.uk', 'Tech & transformation roles', 'Recruitment Agencies', 'active'),
('Career Factory', 'https://career-factory.eu', 'Career coaching & jobs', 'Recruitment Agencies', 'active'),
('Medicopec', 'https://medicopec.mk', 'Medical & healthcare staffing', 'Recruitment Agencies', 'active'),
('NXT Hero', 'https://nxt-hero.com', 'Digital & gaming talent', 'Recruitment Agencies', 'active'),
('Intelligent People', 'https://intelligentpeople.com', 'Creative & marketing staffing', 'Recruitment Agencies', 'active'),
('Evolve Talent', 'https://evolvetalent.eu', 'Tech & digital recruitment', 'Recruitment Agencies', 'active'),
('ITS Jobs We R Online', 'https://itsjobswereonline.com', 'IT job board', 'Recruitment Agencies', 'active'),
('Joanne Hart', 'https://joannehart.co.uk', 'Admin & support staffing', 'Recruitment Agencies', 'active'),
('Rizer Recruitment', 'https://rizerrecruitment.com', 'Tech & niche roles', 'Recruitment Agencies', 'active'),
('Consultason', 'https://consultason.de', 'HR & interim consulting', 'Recruitment Agencies', 'active'),
('Infotech Recruitment', 'https://infotechrecruitment.com', 'IT & software specialists', 'Recruitment Agencies', 'active'),
('Makk Rohr', 'https://makkrohr.com', 'German-speaking tech staffing', 'Recruitment Agencies', 'active'),
('Viru Sourcing', 'https://virusourcing.com', 'IT & digital outsourcing', 'Recruitment Agencies', 'active'),
('Hiber Roy Consultants', 'https://hiberlin-royconsultants.de', 'Executive & HR consulting', 'Recruitment Agencies', 'active'),
('Medipoint', 'https://medipointag.ch', 'Medical & life sciences', 'Recruitment Agencies', 'active'),
('Essmann Beratung', 'https://essmann-beratung.de', 'HR & leadership consulting', 'Recruitment Agencies', 'active'),
('ERSG Global', 'https://ersg-global.com', 'Energy & engineering staffing', 'Recruitment Agencies', 'active'),
('ISIS Technical', 'https://isistechnical.co.uk', 'Technical & engineering roles', 'Recruitment Agencies', 'active'),
('Fortech Consulting', 'https://fortechconsulting.de', 'IT & engineering staffing', 'Recruitment Agencies', 'active'),
('Talentania', 'https://talentania.de', 'Talent acquisition platform', 'Recruitment Agencies', 'active'),
('Career People', 'https://careerpeople.com', 'Sales, marketing & tech jobs', 'Recruitment Agencies', 'active'),
('Tech Global', 'https://techglobal.com', 'Global tech recruitment', 'Recruitment Agencies', 'active'),
('Pantheon Recruitment', 'https://pantheon-recruitment.de', 'Executive & specialist search', 'Recruitment Agencies', 'active'),
('Spartacus IT', 'https://spartacusit.nl', 'Dutch-German IT staffing', 'Recruitment Agencies', 'active'),
('MaxMatch', 'https://maxmatch.de', 'AI-powered job matching', 'Recruitment Agencies', 'active'),
('Zync Group', 'https://zyncgroup.com', 'Tech & digital talent', 'Recruitment Agencies', 'active'),

-- English-speaking companies in Germany
('About You', 'https://corporate.aboutyou.de/de/career/our-jobs', 'E-commerce fashion platform with English job opportunities', 'English Hiring Companies', 'active'),
('Accenture', 'https://www.accenture.com/de-de/careers/jobsearch', 'Global consulting with English-speaking positions in Berlin', 'English Hiring Companies', 'active'),
('Accountable', 'https://join.com/companies/accountable', 'Financial services startup with English job openings', 'English Hiring Companies', 'active'),
('Acemate.ai', 'https://join.com/companies/acemate', 'AI-powered platform offering English-speaking roles', 'English Hiring Companies', 'active'),
('Babbel', 'https://jobs.babbel.com/en/', 'Language learning platform with international team opportunities', 'English Hiring Companies', 'active'),
('Personio', 'https://www.personio.com/about-personio/careers/', 'HR software company with English-speaking work environment', 'English Hiring Companies', 'active'),
('Banxware', 'https://www.banxware.com/careers', 'Fintech startup offering English job opportunities', 'English Hiring Companies', 'active'),
('BASF', 'https://basf.jobs/', 'Chemical industry leader with international English positions', 'English Hiring Companies', 'active'),
('BearingPoint', 'https://www.bearingpoint.com/en/careers/open-roles/', 'Management consulting with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Bettermile', 'https://bettermile.com/careers/', 'Logistics optimization platform with English job openings', 'English Hiring Companies', 'active'),
('Carbon One', 'https://www.carbon.one/#jobs', 'Carbon management startup with English-speaking roles', 'English Hiring Companies', 'active'),
('Caidera', 'https://www.caidera.ai/de/karriere', 'AI technology company offering English job opportunities', 'English Hiring Companies', 'active'),
('Calima', 'https://www.calima.io/jobs', 'Clean energy platform with English-speaking positions', 'English Hiring Companies', 'active'),
('Canva', 'https://www.lifeatcanva.com/en/jobs/', 'Design platform with international English job opportunities', 'English Hiring Companies', 'active'),
('Caresyntax', 'https://www.linkedin.com/company/caresyntax/', 'Healthcare AI company with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Cloover', 'https://cloover.notion.site/Join-us-Cloover-73ec11a2660748ecb6b66be87c10d4b8', 'Clean technology startup offering English job openings', 'English Hiring Companies', 'active'),
('Claire', 'https://clareandme.notion.site/Clare-needs-YOU-3acc2ce1815d402c8c6c6ea0ca5e3fd9', 'Digital assistant platform with English-speaking roles', 'English Hiring Companies', 'active'),
('Elearnio', 'https://careers.elearnio.com/jobs/Careers', 'E-learning platform with English job opportunities', 'English Hiring Companies', 'active'),
('Finmid', 'https://jobs.ashbyhq.com/finmid.com', 'Financial services with English-speaking finance positions', 'English Hiring Companies', 'active'),
('Finanztip', 'https://finanztip.jobs.personio.de/', 'Financial advice platform with English job openings', 'English Hiring Companies', 'active'),
('FICUS', 'https://ficushealth.jobs.personio.com/', 'Healthcare platform with English engineering and product roles', 'English Hiring Companies', 'active'),
('Finoa', 'https://finoa.jobs.personio.com/', 'Digital asset custody with English-speaking opportunities', 'English Hiring Companies', 'active'),
('FION Energy', 'https://www.linkedin.com/company/fion-energy/jobs/', 'Energy technology company with English job opportunities', 'English Hiring Companies', 'active'),
('goodcarbon', 'https://www.linkedin.com/company/goodcarbon/jobs/', 'Carbon management platform with English sales and service roles', 'English Hiring Companies', 'active'),
('GetYourGuide', 'https://www.getyourguide.careers/open-roles', 'Travel platform with international English job opportunities', 'English Hiring Companies', 'active'),
('gematik', 'https://www.gematik.de/stellenangebote/stellenangebote.html', 'Digital health infrastructure with English-speaking positions', 'English Hiring Companies', 'active'),
('JOIN', 'https://join.com/careers#openpositions', 'Recruitment platform with English job opportunities', 'English Hiring Companies', 'active'),
('Jungwild', 'https://jungwild.io/jobs/', 'Digital agency with English-speaking work environment', 'English Hiring Companies', 'active'),
('JustWatch', 'https://jobs.lever.co/justwatch', 'Movie streaming search with English job openings', 'English Hiring Companies', 'active'),
('ETERNO', 'https://careers.eterno.group/en/jobs', 'Business services group with English-speaking opportunities', 'English Hiring Companies', 'active'),
('KAIKO Systems', 'https://job-boards.eu.greenhouse.io/kaikosystems', 'Maritime technology with English job opportunities', 'English Hiring Companies', 'active'),
('KAYAK', 'https://www.kayak.com/careers/berlin/all', 'Travel search platform with English positions in Berlin', 'English Hiring Companies', 'active'),
('kertos', 'https://www.kertos.io/en/jobs', 'Data analytics platform with English job openings', 'English Hiring Companies', 'active'),
('kiron', 'https://www.kiron.ngo/careers#Positions', 'Educational nonprofit with English-speaking opportunities', 'English Hiring Companies', 'active'),
('kittl', 'https://jobs.ashbyhq.com/kittl', 'Design platform with English job opportunities', 'English Hiring Companies', 'active'),
('KNIME', 'https://knime.jobs.personio.de/', 'Data analytics platform with English-speaking positions', 'English Hiring Companies', 'active'),
('Knowunity', 'https://jobs.ashbyhq.com/knowunity', 'Educational platform with English job opportunities', 'English Hiring Companies', 'active'),
('Formo', 'https://eatformo.com/work/', 'Food technology company with English-speaking roles', 'English Hiring Companies', 'active'),
('Forto', 'https://careers.forto.com/forto-jobs/', 'Digital freight platform with English job opportunities', 'English Hiring Companies', 'active'),
('FREE NOW', 'https://job-boards.greenhouse.io/freenow', 'Mobility platform with English positions across Europe', 'English Hiring Companies', 'active'),
('Friendsurance', 'https://www.friendsurance.com/en/careers/', 'Digital insurance with English-speaking opportunities', 'English Hiring Companies', 'active'),
('FUNKE', 'https://karriere.funkemedien.de/de/', 'Media group with English job opportunities', 'English Hiring Companies', 'active'),
('LucaNet', 'https://www.lucanet.com/en/careers/jobs/', 'Financial software with English-speaking positions', 'English Hiring Companies', 'active'),
('Logistica OS', 'https://join.com/companies/logistica-oscom', 'Logistics platform with English job opportunities', 'English Hiring Companies', 'active'),
('Metiundo', 'https://jobs.metiundo.io/eng', 'Property technology with English-speaking roles', 'English Hiring Companies', 'active'),
('Merantix', 'https://careers.merantix.com/companies/deltia-2', 'AI venture studio with English job opportunities', 'English Hiring Companies', 'active'),
('Mercanis', 'https://mercanis.jobs.personio.de/', 'Supply chain platform with English-speaking positions', 'English Hiring Companies', 'active'),
('mgm-tp', 'https://jobs.mgm-tp.com/', 'Technology consulting with English job opportunities', 'English Hiring Companies', 'active'),
('Mindspace', 'https://www.mindspace.me/careers/', 'Coworking spaces with English-speaking opportunities', 'English Hiring Companies', 'active'),
('Needle', 'https://needle.app/careers', 'Customer service platform with English sales and service roles', 'English Hiring Companies', 'active'),
('Peec AI', 'https://peec.ai/careers', 'AI technology company with English job opportunities', 'English Hiring Companies', 'active'),
('pplwise', 'https://pplwise.com/career/', 'HR analytics platform with English-speaking positions', 'English Hiring Companies', 'active'),
('ppro', 'https://www.ppro.com/about-us/careers/', 'Payment technology with English job opportunities', 'English Hiring Companies', 'active'),
('Purpose Green', 'https://purpose-green.jobs.personio.de/', 'Sustainable business solutions with English-speaking roles', 'English Hiring Companies', 'active');

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_recruitment_agencies_updated_at 
    BEFORE UPDATE ON recruitment_agencies 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
